name: "Destory Test Environment"

on:
  workflow_dispatch:
      inputs:
        workspace:
          description: 'Name of workspace to destroy'
          required: true
          default: ''

jobs:
  destroy-terraform:
    name: Destroy Test Environment
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Select branch workspace
      - name: Terraform Workspace
        run: terraform workspace select ${{ github.event.inputs.workspace }}

      # Destroy the workspace
      - name: Terraform Destory
        run: terraform destroy -auto-approve

      # Select default workspace
      - name: Terraform Workspace
        run: terraform workspace select default

      # Delete branch workspace
      - name: Terraform Workspace
        run: terraform workspace delete ${{ github.event.inputs.workspace }}
